//! Bake the built UI into the binary, so the core of formicaria is **one file**.
//!
//! The core — notes and scheduling on a local PC — deliberately spawns nothing and needs
//! no external tool (see `decisions.md`). The one thing still tying it to a checkout was
//! `ui/dist` being read off disk at runtime. Embedding it means `fm-serve` alone *is* the
//! app: copy it anywhere, on any OS, and it runs. Everything else stays an optional
//! feature found on `PATH`.
//!
//! Hand-rolled rather than `rust-embed`/`include_dir`: this is ~40 lines against a
//! dependency, in a crate that is deliberately std-only networking and minimal-deps.
//!
//! A missing `ui/dist` is **not** an error. `cargo build -p fm-serve` on a fresh clone
//! must work before anyone has run `pnpm build`; it just yields an empty table, and the
//! server says so at startup as it always has.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let dist = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../ui/dist");
    // Cargo watches the directory, so a `pnpm build` re-triggers the embed.
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut files = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut files);
    }
    if files.is_empty() {
        println!(
            "cargo:warning=ui/dist is empty or missing — the binary will embed no UI. \
             Run `pixi run build` (or `pnpm -C ui build`) to bundle it."
        );
    }
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the built UI, baked in. Do not edit.\n\
         pub static UI_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        // Forward slashes in both: `include_bytes!` takes them on Windows too, and it
        // spares us escaping backslashes into a Rust string literal.
        out.push_str(&format!("    ({rel:?}, include_bytes!({abs:?})),\n"));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("ui_assets.rs");
    fs::write(&dest, out).expect("write ui_assets.rs");
}

/// Every file under `dir`, as (path relative to the dist root, absolute path), both with
/// forward slashes. The relative one is what a browser asks for; the absolute one is what
/// `include_bytes!` reads at compile time.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            out.push((slashed(rel), slashed(&path)));
        }
    }
}

fn slashed(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}
