//! Bake the built UI into the binary, so the core of formicaria is **one file**.
//!
//! The core — notes and scheduling on a local PC — deliberately spawns nothing and needs
//! no external tool (see `decisions.md`). The one thing still tying it to a checkout was
//! `ui/dist` being read off disk at runtime. Embedding it means `fm-serve` alone *is* the
//! app: copy it anywhere, on any OS, and it runs. Everything else stays an optional
//! feature found on `PATH`.
//!
//! Hand-rolled rather than `rust-embed`/`include_dir`: this is ~40 lines against a
//! dependency, in a crate that is deliberately std-only networking and minimal-deps.
//!
//! A missing `ui/dist` is **not** an error. `cargo build -p fm-serve` on a fresh clone
//! must work before anyone has run `pnpm build`; it just yields an empty table, and the
//! server says so at startup as it always has.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let mut out = String::from("// @generated by build.rs — do not edit.\n");

    // The UI. Without this the binary is not the app.
    embed(
        &root.join("../../ui/dist"),
        "UI_ASSETS",
        "ui/dist is empty or missing — the binary will embed no UI. \
         Run `pixi run build` (or `pnpm -C ui build`) to bundle it.",
        &mut out,
    );

    // **The manual, by the same argument as the UI.** A release user who cannot find the
    // documentation does not have it, and the folder beside the binary is exactly what gets lost
    // when someone copies out just the executable — the case this embedding exists to survive.
    // `docs/book` is generated by `pixi run docs` and gitignored, so like `ui/dist` its absence
    // is a warning and not an error: a fresh clone must still `cargo build -p fm-serve`.
    embed(
        &root.join("../../docs/book"),
        "MANUAL_ASSETS",
        "docs/book is empty or missing — the binary will embed no manual, and the in-app \
         Help button will 404. Run `pixi run docs` to render it.",
        &mut out,
    );

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("ui_assets.rs");
    fs::write(&dest, out).expect("write ui_assets.rs");
}

/// Bake one directory into one `&[(path, bytes)]` table named `name`.
///
/// Shared by the UI and the manual because the job is identical — walk a tree, emit
/// `include_bytes!` for each file — and the only thing that ever differed was the warning text.
fn embed(dir: &Path, name: &str, warning: &str, out: &mut String) {
    // Cargo watches the directory, so a rebuild of either input re-triggers the embed.
    println!("cargo:rerun-if-changed={}", dir.display());

    let mut files = Vec::new();
    if dir.is_dir() {
        collect(dir, dir, &mut files);
    }
    if files.is_empty() {
        println!("cargo:warning={warning}");
    }
    files.sort();

    out.push_str(&format!("pub static {name}: &[(&str, &[u8])] = &[\n"));
    for (rel, abs) in &files {
        // Forward slashes in both: `include_bytes!` takes them on Windows too, and it
        // spares us escaping backslashes into a Rust string literal.
        out.push_str(&format!("    ({rel:?}, include_bytes!({abs:?})),\n"));
    }
    out.push_str("];\n");
}

/// Every file under `dir`, as (path relative to the dist root, absolute path), both with
/// forward slashes. The relative one is what a browser asks for; the absolute one is what
/// `include_bytes!` reads at compile time.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, String)>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            out.push((slashed(rel), slashed(&path)));
        }
    }
}

fn slashed(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}
